### ISSUE TITLE
Error : MC is not defined

### ISSUE THREAD

**Issue by IamColonel** [kabirsingh2004/JUGNU-MUSIC#41]
![image_2022-11-30_203329457](https://user-images.githubusercontent.com/86377569/204891510-62e16318-93e2-49e7-8e2a-7b9ab5235e2a.png)

**Comment by Sudo-null7** [comment]
this appears as a distude error and will need @kabirsingh2004 and crew to fix this error

**Comment by kabirsingh2004** [comment]
show ss of terminal error

**Comment by Sudo-null7** [comment]
![image](https://user-images.githubusercontent.com/70843928/205727928-fbfe3cf6-8ed6-4105-8062-73b496263d5c.png)
![image](https://user-images.githubusercontent.com/70843928/205727966-d5c8c7fb-7d61-4196-a9ee-b40b46fd1478.png)

Nothing is outputted to console

**Comment by Sudo-null7** [comment]
![image](https://user-images.githubusercontent.com/70843928/205728146-f4faa132-0398-4b89-b544-7d5465e5d9e1.png)
This looks like the new error (nothing change) happens then Posting a YT Link in its own channel

![image](https://user-images.githubusercontent.com/70843928/205728267-a7a01f60-0958-493e-9945-56fd68c24ad8.png)
This is what happens when you type ("Among us") in to its music channel


![image](https://user-images.githubusercontent.com/70843928/205728743-1b3d29e4-85f8-4e53-aba0-067a0c089319.png)
This is output from /play command with link

![image](https://user-images.githubusercontent.com/70843928/205728955-d0c07baf-ab40-4a0d-b4a3-e68c22091d57.png)

This is output from /play with song name instead of a link

![image](https://user-images.githubusercontent.com/70843928/205729133-ed223a81-50eb-4c7a-a41e-355a32244f27.png)
This is the console the whole time of running all of these commands

**Comment by Sudo-null7** [comment]
```
Found a Error...
PlayingError: FFmpeg/avconv not found!
Id: <YT ID>
Name: <Song Name>
------------------------------------------------------------------------------------------
Found a Error...
PlayingError: Cannot destructure property 'duration' of 'queue.songs[0]' as it is undefined.
```

**Comment by Sudo-null7** [comment]
Close this @kabirsingh2004 it appears to be fixed?

**Comment by Sudo-null7** [comment]
![image](https://user-images.githubusercontent.com/70843928/206873875-3a0c3c51-7daf-4273-ae0a-9763614dd279.png)
You need to get FFmpeg
